persons=['Helen','Amy','Sam']
message="would you like to have dinner with me?"
print(persons[0]+","+message)
print(persons[1]+","+message)
print(persons[2]+","+message)
print(persons[2]+" can not have dinner with me.")
persons[2]='Linda'
print(persons[0]+","+message)
print(persons[1]+","+message)
print(persons[2]+","+message)
print("I have found a bigger table.")
persons.insert(0,'honda')
persons.insert(1,'yamaha')
persons.append('suzuki')
print(persons[0]+","+message)
print(persons[1]+","+message)
print(persons[2]+","+message)
print(persons[3]+","+message)
print(persons[4]+","+message)
print(persons[5]+","+message)
print("I can only invite two person.")
popped_person=persons.pop()
print("I am sorry to tell you that I can not invite you to have dinner,"+popped_person)
popped_person=persons.pop()
print("I am sorry to tell you that I can not invite you to have dinner,"+popped_person)
popped_person=persons.pop()
print("I am sorry to tell you that I can not invite you to have dinner,"+popped_person)
popped_person=persons.pop()
print("I am sorry to tell you that I can not invite you to have dinner,"+popped_person)
print("You can still have dinner with me,"+persons[0]+".")
print("You can still have dinner with me,"+persons[1]+".")
del persons[0]
del persons[1]
print(persons)
